[package]
name = "yew-counter"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-logger = "0.2.0"
log = "0.4.17"
yew = { version = "0.20.0", features = ["csr"] }
