[package]
name = "library"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen-futures = "0.4.34"
wasm-logger = "0.2.0"
log = "0.4.17"